// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Xuw0UcpdM1eDXg95rtenZjrwnYDXbF8',
    appId: '1:413386302976:web:204ae22735bfea09c21ae5',
    messagingSenderId: '413386302976',
    projectId: 'holbegram-937c3',
    authDomain: 'holbegram-937c3.firebaseapp.com',
    storageBucket: 'holbegram-937c3.firebasestorage.app',
    measurementId: 'G-Q4K0YR26R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6eh0BklNv-27RqOD5rtlIUWF2mfkElR4',
    appId: '1:413386302976:android:87b49d9c3642d298c21ae5',
    messagingSenderId: '413386302976',
    projectId: 'holbegram-937c3',
    storageBucket: 'holbegram-937c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA24X_EUMyyAbEMJHep5qWqN-rmne0Iv4',
    appId: '1:413386302976:ios:f720644d11960f16c21ae5',
    messagingSenderId: '413386302976',
    projectId: 'holbegram-937c3',
    storageBucket: 'holbegram-937c3.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA24X_EUMyyAbEMJHep5qWqN-rmne0Iv4',
    appId: '1:413386302976:ios:f720644d11960f16c21ae5',
    messagingSenderId: '413386302976',
    projectId: 'holbegram-937c3',
    storageBucket: 'holbegram-937c3.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Xuw0UcpdM1eDXg95rtenZjrwnYDXbF8',
    appId: '1:413386302976:web:ec381ced47c7ea49c21ae5',
    messagingSenderId: '413386302976',
    projectId: 'holbegram-937c3',
    authDomain: 'holbegram-937c3.firebaseapp.com',
    storageBucket: 'holbegram-937c3.firebasestorage.app',
    measurementId: 'G-VGQ6MFCP7M',
  );
}
